document.write('<!-- CDN for jquery -->');
document.write('<script src="https://code.jquery.com/jquery-1.12.4.js" integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU=" crossorigin="anonymous"></script>');
document.write('<!-- CDN for bootstrap -->');
document.write('<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>');
document.write('<script src="/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>');
document.write('');
document.write('<footer class="pt-4 my-md-5 pt-md-5 border-top">');
document.write('    <div class="row">');
document.write('      <div class="col-12 col-md">');
document.write('        <img class="mb-2" src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">');
document.write('        <small class="d-block mb-3 text-muted">&copy; 2022</small>');
document.write('      </div>');
document.write('      <div class="col-6 col-md">');
document.write('        <h5>About</h5>');
document.write('        <ul class="list-unstyled text-small">');
document.write('          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Link #1</a></li>');
document.write('          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Link #2</a></li>');
document.write('          <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Link #3</a></li>');
document.write('        </ul>');
document.write('      </div>');
document.write('    </div>');
document.write('  </footer>');
document.write('</body>');
document.write('</html>');
